name: Deploy

on:
  push:
    branches: [ "add-terraform-workflow" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set JDK v18
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'corretto'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.5.1

      - name: Run tests
        run: ./gradlew test

      - name: Build
        run: ./gradlew clean build